server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pesticide?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

fileUpdatePath: d:/pesticide/
